### ISSUE TITLE
名字含中文的文件会被下载成"file"

### ISSUE THREAD

**Issue by slikie** [zqqian/baidulixiandown#1]
最新macOS +最新Chrome +最新 Aria2c 配合loveno.net使用的 能够复现。还需要什么信息请回复我。

**Comment by zqqian** [comment]
新版本会做出一些改进
因为下载链接是/file?xxxx..... 所以会被一些软件认为文件的名字就是file

比如在windows中直接复制下载地址到迅雷中，迅雷给文件的命名就是file，并按照这个名字下载。
但是点击下载链接，然后在浏览器弹出的下载框中选择迅雷下载名字就会恢复正常的名字。
