### ISSUE TITLE
是否可以提供更详细的教程

### ISSUE THREAD

**Issue by ACGunion** [zqqian/baidulixiandown#2]
您好。我希望详细了解一下您开发的程序的使用方式。能否提供更详细的教程，因为我了解到PCS的API申请已经暂停了，请问应该如何获取相关的API密钥？

**Comment by zqqian** [comment]
你好，关于PCS api的申请我也没有办法，我是在很久以前开放申请的时候申请的。

**Comment by ACGunion** [comment]
您好，我希望继续获得一些帮助。
关于config.php文件中应用目录名是否可以自由填写
getkey.php文件中“client_id”字段填写百度开发者中心对应的“APP KEY”
“client_secret”字段填写“Secret Key”
“redirect_uri”字段填写"网址/getkey.php"
login.js也对应上面的信息填写完成后，能登录百度授权，但是返回到filelist.php 回报 500错误，请问是我填写错误还是其他问题？
我是用的是PHP5.6+Apache，错误日志如下

> [Fri Oct 28 04:53:31 2016] [error] [client 10.0.0.102] PHP Parse error:  syntax error, unexpected end of file in /var/www/webroot/ROOT/filelist.php on line 177, referer: http://xxxx/login.html

**Comment by zqqian** [comment]
应用目录名不可以自由填写，这个在申请API的时候是已经固定了的
filelist.php我更新了一下，这个是我现在服务器上运行的版本，可以试一下。
如果还是有问题就把第二行的err_report注释掉，把错误信息发过来。

**Comment by ACGunion** [comment]
感谢您的帮助，您更新后已经可以正常使用了。
