### ISSUE TITLE
是不是没有PCS API权限就不能使用啊？

### ISSUE THREAD

**Issue by TonyWang8904** [zqqian/baidulixiandown#5]
了解到百度PCS API在9月8日已经停止申请了，请问没有这个API是不是就不能使用你这个啊？

**Comment by digiouyang** [comment]
Tony,

你好，我和你有同样的苦恼，想做一个使用百度PCS API的App，然后提交使用申请快一个月也没有回音，请问你是在哪里知道百度PCS API在9月8日已经停止申请了，有官方的帖子吗？ 有什么类似的证据麻烦给个URL，谢谢。
